version: '0.1'

services:
  aur-mirror:
    build: https://github.com/tacattack-04/mini-mirror.git#unstable
    container_name: aur-mirror-builder
    user: builder
    ports:
      - "8080:8080"
    volumes:
      - ./packages.txt:/home/builder/packages.txt:ro
      - mirror-data:/srv/http/mirror
      - aur-cache:/tmp/aur-builds
    environment:
      - MIRROR_NAME=my-custom-mirror
      - MIRROR_DIR=/srv/http/mirror
      - UID=1000
      - GID=1000
      - CRON_SCHEDLUE=0 */12 * * *
    restart: unless-stopped
    # Run the build process once, then keep lighttpd running
    command: /bin/bash -c "/home/builder/aur-build-mirror.sh && lighttpd -f /etc/lighttpd/lighttpd.conf -D"

volumes:
  mirror-data:
    driver: local
  aur-cache:
    driver: local
