services:
  aur-mirror:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: aur-mirror-builder
    network_mode: bridge
    dns:
      - 1.1.1.1
      - 8.8.8.8
    user: builder
    ports:
      - "8080:8080"
    volumes:
      - ./startup/packages.txt:/home/builder/packages.txt:ro
      - mirror-data:/srv/http/mirror
      - aur-cache:/tmp/aur-builds
    environment:
      - MIRROR_NAME=my-custom-mirror
      - MIRROR_DIR=/srv/http/mirror
      - UID=1000
      - GID=1000
      - CRON_SCHEDULE=0 */12 * * *
    restart: unless-stopped
    # Run the build process once, then keep lighttpd running
    command: /bin/bash -c "/home/builder/aur-build-mirror.sh && lighttpd -f /etc/lighttpd/lighttpd.conf -D"

volumes:
  mirror-data:
    driver: local
  aur-cache:
    driver: local
