version: '0.1'

services:
  aur-mirror:
    image: TacAttack-04/Mini-Mirror
    container_name: aur-mirror-builder
    ports:
      - "8080:8080"
    volumes:
      - ./packages.txt:/home/builder/packages.txt:ro
      - mirror-data:/srv/http/mirror
      - aur-cache:/tmp/aur-builds
    environment:
      - MIRROR_NAME=my-custom-mirror
      - MIRROR_DIR=/srv/http/mirror
    restart: unless-stopped
    # Run the build process once, then keep lighttpd running
    command: /bin/bash -c "sudo /home/builder/aur-build-mirror.sh && sudo lighttpd -f /etc/lighttpd/lighttpd.conf -D"

volumes:
  mirror-data:
    driver: local
  aur-cache:
    driver: local
